        @startuml

actor Pengguna
participant Ticket
participant Order
participant OrderExpiration
participant Payment
queue MessageBroker

Pengguna -> Ticket: Permintaan lihat kategori tiket
Ticket --> Pengguna: Kategori tiket

Pengguna -> Ticket: Permintaan lihat tiket berdasarkan kategori
Ticket --> Pengguna: Tiket berdasarkan kategori

Pengguna -> Order: Buat order tiket
Order -> Ticket: Cek ketersediaan tiket
Ticket --> Order: Tiket tersedia
Order -> MessageBroker: Kirim event order berhasil dibuat
MessageBroker --> Order: OK
Order --> Pengguna: Kode transaksi order
MessageBroker --> Ticket: Event order dibuat
Ticket -> Ticket: Ubah tiket menjadi tidak tersedia
MessageBroker --> OrderExpiration: Event order dibuat
    OrderExpiration -> OrderExpiration: Buat timer untuk membatalkan order
OrderExpiration -> MessageBroker: Kirim event order expire
MessageBroker --> OrderExpiration: OK
MessageBroker --> Order: Event order expire
Order -> Order: Ubah status order menjadi expire

Pengguna -> Payment: Buat pembayaran
Payment -> Order: Minta data pesanan
Order --> Payment: Data pesanan
Payment -> MessageBroker: Kirim event pembayaran berhasil
Payment --> Pengguna: Pembayaran berhasil

MessageBroker --> Order: Event payment dibuat
Order -> Order: Ubah status order menjadi selesai
@enduml